### ISSUE TITLE
how does this handle an overflow of the ballot number

### ISSUE THREAD

**Issue by fogti** [spacejam/paxos#1]
(I wasn't able to find any documentation at all about how any implementation handles this...)
I would like to know how this system would behave if it was "spammed" with updates and thus the `Ballot` number would reach `usize::MAX`. I didn't find an explicit mention of it in the original CASPaxos paper, and would like to know how this could be handled. Even suggestions how it may be handled would be good enough, probably...

**Comment by ghost** [comment]
Ballot number is of type `u64`. If the ballot number is bumped ("spammed") every nanosecond (which is unrealistic since modern computer and networks are not that fast), it would take 585 years to overflow. Fortunately or unfortunately, we won't be alive by then.
